### PR TITLE
Revamp directory structures

### PR DESCRIPTION
**Pull request by Sharad24**

### CODE REVIEW

**Comment by Sharad24** [comment]
Revamp directory structure as so:
```
jigglypuffRL
    deeprl
        common/
            actor_critic.py
            trainer.py
        agents/
            dqn
                dqn.py
    classicalrl

```

**Comment by Sharad24** [comment]
Also, I've added tests for all current `agents` except `DQN` (Idk why it was giving an error) and Bandit algorithms in `classicalrl`

**Comment by ajaysub110** [comment]
I'll review once you're done with this

**Comment by Sharad24** [comment]
I'm done

**Comment by ajaysub110** [comment]
Oh okay. Taking a look now

**Comment by ajaysub110** [comment]
Shall we merge?

**Comment by Sharad24** [comment]
I'm going through some coverage reports to see what all things are missing in the files I'm trying to cover. Will push some minor changes with `pragma: no cover`

**Comment by Sharad24** [comment]
Ok, going to merge once LGTM is finished

**Comment by Sharad24** [comment]
Merging

**Pull request merged**
