### PR TITLE
Minor error in categorical DQN

### PR DESCRIPTION
**Pull request by Het-Shah**
There was a minor error in categorical DQN. Sorry for this.

### CODE REVIEW

**Comment by ajaysub110** [comment]
A few things:
- Can you add the `noisy_dqn` and `categorical_dqn` hyperparameters to the dictionary in `get_hyperparams`? Saving these will help keep track of experiments run using different kinds of DQN.
- The categorical DQN doesn't seem to learn anything even in CartPole. Have you tested it?
- Memory usage for categorical DQN seems oddly high. Any reason for this?

**Comment by Het-Shah** [comment]
> Can you add the noisy_dqn and categorical_dqn hyperparameters to the dictionary in get_hyperparams? Saving these will help keep track of experiments run using different kinds of DQN.

I'll add this no worries.

> The categorical DQN doesn't seem to learn anything even in CartPole. Have you tested it?

It should do now after this commit that I made, it did for me. 

> Memory usage for categorical DQN seems oddly high. Any reason for this?

I'll check for this.

**Comment by Het-Shah** [comment]
categorical_dqn

It is training for me @ajaysub110. Maybe try increasing the number of epochs. Have you tried the code from this pr?

**Comment by ajaysub110** [comment]
OK. I'll try running it again. Yes, I had used the code from this PR. When you train, is your RAM usage normal?

**Comment by Het-Shah** [comment]
Yea. I did not see any abnormality in the RAM usage.

**Comment by ajaysub110** [comment]
Screenshot from 2020-04-20 14-28-03

Ran it on CPU again. RAM usage keeps increasing (even after this)

**Comment by Het-Shah** [comment]
This is weird. I don't see a reason for this clogging of RAM. Anyways, I'll still look into this again.

**Comment by Het-Shah** [comment]
Can you try any other variant(like `noisy_dqn`) and see if they also take up this much of RAM?

**Comment by ajaysub110** [comment]
Yeah, others do too. I think it might be happening due our large replay memory. This would also explain why it happens only on CPU and not on Colab.

**Comment by ajaysub110** [comment]
Cool then, merging this

**Pull request merged**
