### PR TITLE
Refactor DDPG

### LINKED ISSUE #55: Refactor DDPG to new Actor Critic
Refer #52

### PR DESCRIPTION
**Pull request by ajaysub110**
Resolves #55

### CODE REVIEW

**Comment by ajaysub110** [comment]
Travis will still fail since PPO1 and VPG are not yet refactored

**Comment by Sharad24** [comment]
Also, if possible please think about the tests that we have to write for each function. We should follow https://github.com/hill-a/stable-baselines ideally

**Comment by ajaysub110** [comment]
> Also, if possible please think about the tests that we have to write for each function. We should follow https://github.com/hill-a/stable-baselines ideally

Should they be done here or as another PR?

**Comment by Sharad24** [comment]
I think it would be good to get the algorithms written first, so probably in another PR

**Comment by ajaysub110** [comment]
Cool, merging then

**Comment by ajaysub110** [comment]
Atleast build is passing now :)

**Comment by Sharad24** [comment]
With `# noqa`. Lol

**Pull request merged**
