### PR TITLE
Distributional DQN 

### PR DESCRIPTION
**Pull request by Het-Shah**
Have a look at it. I tried this on CartPole-v0 reached 200 average reward after 200 epochs.
#36

### CODE REVIEW

**Comment by Het-Shah** [comment]
merge this i made some corrections to dqn in these which are not there. After is only the A3C one is left.

**Comment by Sharad24** [comment]
Cool!

**Comment by Sharad24** [comment]
Has some conflicts?

**Comment by Het-Shah** [comment]
wait i'll resolve

**Comment by Het-Shah** [comment]
It doesn't have now. Was a small conflict in `__main__`

**Comment by Het-Shah** [comment]
Now you can merge this.

**Comment by Sharad24** [comment]
Yeah, was just waiting for checks.

**Pull request merged**
