### PR TITLE
VecEnvs

### PR DESCRIPTION
**Pull request by Het-Shah**
Let me know your thoughts about this implementation. This will change almost all algorithms.

### CODE REVIEW

**Comment by Het-Shah** [comment]
For now, I have kept this file inside common I guess it will be better to have a new directory for this.

**Comment by Sharad24** [comment]
I think it would be good to shift the env initialisation also inside the constructor. And have an option to pass some envs. For e.g. if Env name is cart pole and number of envs is 32. There are 32 processes instantiated in the constructor

We also might have to check how it helps in training, as it just slows it it’s not very helpful as such? Can you benchmark this on any one algo?

**Comment by Het-Shah** [comment]
> I think it would be good to shift the env initialisation also inside the constructor. And have an option to pass some envs.

This is the eventual aim of the whole process. Like maybe have 2 different envs that train in parallel.

> We also might have to check how it helps in training, as it just slows it it’s not very helpful as such? Can you benchmark this on any one algo?

I am currently trying to incorporate this in DQN. It'll take some time refactoring the code. Till then let me know if there are any errors that you can find.

**Comment by Sharad24** [comment]
Just keep this up to date please? I'm going to add code somewhat dependent on it.

**Comment by Het-Shah** [comment]
Everything seems fine to me. Just correct this build error.

**Comment by Het-Shah** [comment]
Also, should we move these files to a different directory?

**Comment by Sharad24** [comment]
I think it's ok in `common` for now

**Comment by Sharad24** [comment]
@ajaysub110

**Comment by ajaysub110** [comment]
Looks good to me!

**Pull request merged**
